/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:596cadbd-f84b-48bf-bcd6-7991b298f57d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5HFGfpxID",
    "aws_user_pools_web_client_id": "3g3u1oqcs5731m3qs7ros6abi4",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://35qo44hizbedre7p62safg4i2q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vhe56ugeorcdve6oplzv6vqava",
    "aws_user_files_s3_bucket": "bucketnotes23526-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
